App\Entity\Trick:
    properties:
        title:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        description:
            - NotBlank: ~

App\Entity\Comment:
    properties:
        content:
            - NotBlank: ~